version: '3.9'
name: 'rinha-de-backend'

services:
  db-postgresql:
    image: postgres:15.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 60s
    #   resources:
    #     limits:
    #       cpus: '0.8'
    #       memory: '1.5GB'
    # networks:
    #   - app-network
  
  cache-redis:
    image: redis:latest
    ports:
      - "6379:6379"


# networks:
#   app-network:
